spring.application.name=decisionflow

# URL: адрес, порт и имя базы данных, которую ты создала
spring.datasource.url=jdbc:postgresql://localhost:5432/decisionflow_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Драйвер
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Jira
jira.base-url=https://annavalova2004.atlassian.net
jira.username=annavalova2004@gmail.com
jira.api-token=ATATT3xFfGF0UmOdSoj8HR2gF5xA-Ea9Z-kTcsJI391FUSzdzSfSXos-htfCwfTxiXUBbCKnIXldQ1ewsQmTs4Lc2Vo2NwiIcrIqDSowhD--rQnLzIFIB2cKNJC3uSk-1VMwcQcSngRR8VChGmrDiyTMUL8FgBFZ_asbGxavPqTMkXxqUZVsMgg=F39B513E