spring.application.name=decisionflow

# URL: адрес, порт и имя базы данных, которую ты создала
spring.datasource.url=jdbc:postgresql://localhost:5432/decisionflow_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Драйвер
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect